language: node_js
node_js:
  - 0.10
before_install:
  - sudo add-apt-repository ppa:rethinkdb/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install rethinkdb -y
before_script:
  - sudo rethinkdb --io-threads 2048 --daemon
  - sleep 5